version: "3.9"

volumes:
  db-data:
  cache:

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  msg-flow:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env